### ISSUE TITLE
make and, or, xor, add - variadic

### ISSUE THREAD

**Issue by drom** [circt/circt#10]
Currently and, or, xor, add operations are binary. They can be as well defined as variadic.
* [x] `and`
* [x] `or`
* [x] `xor`
* [x] `add`

**Comment by tobiasgrosser** [comment]
@drom added support for variadic and/or/xor in #12. I updated this issue accordingly. "Add" is still open.

**Comment by drom** [comment]
@tobiasgrosser will add the add tomorrow

**Comment by drom** [comment]
done

**Comment by drom** [comment]
make `mul` variadic too.
