### ISSUE TITLE
Modernize cmake build logic

### ISSUE THREAD

**Issue by lattner** [circt/circt#4]
Since this repo started, the MLIR projected added a bunch of CMake support to make it easier to have out of tree dialects etc.

See more details and an example in this patch:
https://reviews.llvm.org/D77133

More generally, the existing cmake stuff should be reviewed, and I think there are a couple of hacks that would be great to fix.

**Comment by stephenneuendorffer** [comment]
I just saw this, but I've already fixed up the cmake stuff so that it matches the conventions, in particular, it reads everything from the llvm exported configuration.  There is some stuff about out of tree configuration for circt users which still needs to get added.

**Comment by lattner** [comment]
@stephenneuendorffer is this true of the circt code I checked in?  The cmake stuff there is best described as hacky - could you take a look at it?

**Comment by stephenneuendorffer** [comment]
Yeah, I already fixed it up...

**Comment by lattner** [comment]
Oh awesome, thank you so much!!

**Comment by stephenneuendorffer** [comment]
I should clarify that this changes the build process so that circt is an out-of-tree project, rather than an LLVM_EXTERNAL_PROJECT.   I've updated the docs to reflect.
